# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxKzvqyT_xYLrN0JhX46yJHmquu0rgjr
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Escolher as ações
tickers = ['KO', 'TSLA']
data = yf.download(tickers, start="2023-01-01", end="2024-01-01")['Close']

# 2. Calcular retornos diários
returns = data.pct_change().dropna()

# 3. Métricas de Risco
volatility = returns.std() * np.sqrt(252) * 100 # Volatilidade anualizada
total_return = (data.iloc[-1] / data.iloc[0] - 1) * 100

# 4. Cálculo Simples do Sharpe Ratio (Assumindo Risk-Free Rate de 0 para simplificar)
sharpe_ratio = (returns.mean() / returns.std()) * np.sqrt(252)

# 5. Visualização Profissional
plt.figure(figsize=(10, 6))
returns.cumsum().plot()
plt.title('Cumulative Returns: KO vs TSLA')
plt.ylabel('Growth (1.0 = 100%)')
plt.grid(True)
plt.savefig('portfolio_performance.png') # Salva a imagem para o seu GitHub
plt.show()

print(f"--- Relatório de Risco vs Retorno ---")
for t in tickers:
    print(f"{t}: Retorno Total: {total_return[t]:.2f}% | Volatilidade: {volatility[t]:.2f}% | Sharpe: {sharpe_ratio[t]:.2f}")